# Generated by Django 4.2.3 on 2023-07-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acionamento', models.CharField(max_length=50)),
                ('data_acionamento', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('position', models.IntegerField(primary_key=True, serialize=False, verbose_name='Posição')),
                ('movie', models.CharField(max_length=255, verbose_name='Filme')),
                ('year', models.DateField(verbose_name='Ano')),
                ('duration', models.CharField(max_length=255, verbose_name='Duração')),
                ('rating', models.CharField(max_length=255, verbose_name='Classificação indicativa')),
                ('rate', models.FloatField(verbose_name='Nota')),
            ],
        ),
    ]
